###############
### WINDOWS ###
###############
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class *, suppress_event maximize,

# Fix some dragging issues with XWayland
windowrule {
	name = fix-dragging-xwayland
	match:class = ^$
	match:title = ^$
	match:xwayland = true
	match:float = true
	match:fullscreen = false
	match:pin = false

	no_focus = on
}

# Screensharing on Linux
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start xdg-desktop-portal-hyprland.service

# Make Minecraft stop launching floating
windowrule = tile on, match:title ^Minecraft\*.*

